id: global_trend_monitor
namespace: demo.monitor
tasks:
  # 1. READ SIMULATED RAW DATA
  - id: read_raw_data
    type: io.kestra.plugin.core.storage.ReadFile
    from: "kestra://data/raw_news_dump.txt"

  # 2. PERFORM GEMINI ANALYSIS
  - id: analyze_trends
    type: io.kestra.plugin.servertribe.google.gemini.GenerateContent
    client: default
    model: gemini-2.5-flash
    contents:
      - text: |
          Analyze the raw news data below. Identify the top 3 emerging global trends.
          Format your output STRICTLY as a JSON array of objects with the keys:
          "trend_name" (short title), "summary" (100-word summary), and "category" (single word like 'TECH', 'REGULATION', 'CLIMATE').
          Raw Data: {{ outputs.read_raw_data.value }}
    format: JSON

  # 3. PUBLISH REPORT DATA
  - id: write_report_data
    type: io.kestra.plugin.core.storage.CreateFile
    filename: trend-report.json
    contents: "{{ outputs.analyze_trends.text }}"

triggers:
  - id: daily_schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 8 * * *"
